<div class="section no-pad-bot" id="index-banner">
        <div class="container">
            <a class='dropdown-button btn btn-flat white-text' id="name" href='#' data-activates='dropdown1' style="margin: 10px"><i class="fa fa-user"></i></a>
            <!-- Dropdown Structure -->
            <ul id='dropdown1' class='dropdown-content' style="margin: 10px">
                <li><a href="#account" class="red-text"><i class="fa fa-user"></i>Tài khoản</a></li>
                <li class="divider"></li>
                <li><a href="#!" class="red-text" onclick="logout();"><i class="fa fa-sign-out"></i>Đăng xuất</a></li>
            </ul>
            <a class="btn-floating btn-large halfway-fab waves-effect waves-light red"><i class="fa fa-plus"></i></a>
          <div class="row center">
            <div class='btn btn-flat white-text' href='#' style="display: table; margin: 0 auto; text-align: center;"><img src="./img/wallet.png" style="width:60px;margin: 0 auto;"><br><i id="wallet_name"></i></div><br><span id="wallet_balance" class="white-text"></span>
          </div>
          <br>
			  <div class="row">
				<div class="col s12">
				  <ul class="tabs" style="overflow-x:hidden;">
					<li class="tab col s4"><a href="#test1">Last Month</a></li>
					<li class="tab col s4"><a class="active" href="#test2">This month</a></li>
					<li class="tab col s4"><a href="#test3">Future</a></li>
				  </ul>
				</div>
			  </div>
        </div>
</div>

<div id="account" class="modal" >
    <div class="modal-content">
        <h4>Modal Header</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>