<div class="section no-pad-bot" id="index-banner">
        <div class="container">
            <a class='dropdown-button btn btn-flat white-text' id="name" href='#' data-activates='dropdown1' style="margin: 10px"><i class="fa fa-user"></i></a>
            <!-- Dropdown Structure -->
            <ul id='dropdown1' class='dropdown-content' style="margin: 10px">
                <li><a href="#my_account" class="red-text"><i class="fa fa-user"></i>Tài khoản</a></li>
                <li class="divider"></li>
                <li><a href="#!" class="red-text" onclick="logout();"><i class="fa fa-sign-out"></i>Đăng xuất</a></li>
            </ul>
            <a class="btn-floating btn-large halfway-fab waves-effect waves-light red" href="#add_transaction"><i class="fa fa-plus"></i></a>
          <div class="row center">
            <a class='btn btn-flat white-text' href='#wallet' style="display: table; margin: 0 auto; text-align: center;"><img src="img/wallet.png" style="width:60px;margin: 0 auto;"><br><i id="wallet_name"></i></a><span id="wallet_balance" class="white-text"></span>
              <input id="current_wallet" type="hidden">
          </div>
          <br>
            <!--
			  <div class="row">
				<div class="col m8 offset-m2 s12">
				  <ul class="tabs" style="overflow-x:hidden;">
					<li class="tab col s4"><a href="#">Past</a></li>
					<li class="tab col s4"><a class="active" href="#">This month</a></li>
					<li class="tab col s4"><a href="#">Future</a></li>
				  </ul>
				</div>
			  </div>
          -->
        </div>
</div>
<br>
<div class="container" id="transaction_list">
</div>
<div id="my_account" class="modal modal-fixed-footer">
    <div class="modal-header red lighten-2 white-text">
        <h4>My Account</h4>
    </div>
    <div class="modal-content">
		 <div class="row">
		<form class="col s12" onsubmit="return false">
		  <div class="row">
			<div class="input-field col s12">
			  <input id="my_account_email" value="" type="email" disabled>
			  <label for="my_account_email">Email</label>
			</div>
		  </div>
		  <div class="row">
			<div class="input-field col s12">
			  <input id="my_account_name" type="text">
			  <label for="my_account_name">Your name</label>
			</div>
		  </div>
		  <div class="row">
			<div class="input-field col s12">
			  <input id="my_account_old_password" type="password" required>
			  <label for="my_account_old_password">Current Password</label>
			</div>
		  </div>
		  <div class="row">
			<div class="input-field col s6">
			  <input id="my_account_new_password" type="password">
			  <label for="my_account_new_password">New Password</label>
			</div>
			<div class="input-field col s6">
			  <input id="my_account_new_password_retype" type="password">
			  <label for="my_account_new_password_retype">Retype New Password</label>
			</div>
		  </div>
	  </div>
    </div>
    <div class="modal-footer">
        <button id="my_account_button" class="modal-action waves-effect waves-light btn red lighten-2">Update</button>
    </div>
    </form>
</div>

<div id="wallet" class="modal modal-fixed-footer" >
    <div class="modal-header red lighten-2 white-text">
        <h4>Select Wallet</h4>
    </div>
    <div class="modal-content">
		<div class="row" id="wallet_list">
		</div>
    </div>
	<div class="modal-footer">
      <a href="#add_wallet" class="modal-action waves-effect waves-light btn red lighten-2">Add Wallet</a>
    </div>
</div>

<div id="currency" class="modal modal-addition">
    <div class="modal-header red lighten-2 white-text">
        <h4>Currency</h4>
    </div>
    <div class="modal-content">
		<div class="row" id="currency_list">
		</div>
    </div>
</div>

<div id="category" class="modal modal-addition modal-fixed-footer">
    <div class="modal-header red lighten-2 white-text">
        <h4>Category</h4>
    </div>
    <div class="modal-content">
		<div class="row" id="category_list_expense">
		</div>
		<div class="row" id="category_list_income">
		</div>
    </div>
    <div class="modal-footer red lighten-2">
        <div class="col s12">
            <ul class="tabs red lighten-2">
                <li class="tab col s6"><a class="active white-text" href="#category_list_expense">Expense</a></li>
                <li class="tab col s6"><a class="white-text" href="#category_list_income">Income</a></li>
            </ul>
        </div>
    </div>
</div>

<div id="add_transaction" class="modal modal-fixed-footer" >
    <div class="modal-header red lighten-2 white-text">
        <h4>Add Transaction</h4>
    </div>
    <div class="modal-content">
		 <div class="row">
		<form class="col s12" onsubmit="return false">
        <div class="input-field col s12" onclick="$('#category').modal('open');">
            <i class="prefix" id="update_add_category_icon"><img class="circle responsive-img" src="img/icon_not_selected.png"></i>
            <input id="add_transaction_category" type="text" placeholder="Category" required>
            <input id="add_transaction_category_id" type="hidden">
        </div>
		<div class="input-field col s12">
          <i class="fa fa-dollar prefix"></i>
          <input id="add_transaction_amount" type="number" placeholder="How much?" required>
        </div>
		<div class="input-field col s12">
          <i class="fa fa-pencil prefix"></i>
          <input id="add_transaction_note" type="text" placeholder="Note" required>
        </div>
        <div class="input-field col s12">
            <i class="fa fa-calendar prefix"></i>
            <input id="add_transaction_date" type="date" placeholder="Date" class="datepicker" required>
        </div>
        <div class="input-field col s12" onclick="$('#wallet').modal('open');">
            <i class="prefix" id="category_icon"><img class="circle responsive-img" src="img/wallet.png"></i>
            <input id="add_transaction_wallet" type="text" placeholder="Wallet">
            <input id="add_transaction_wallet_id" type="hidden">
        </div>
	  </div>
        
    </div>

    <div class="modal-footer">
        <button id="add_transaction_button" class="modal-action waves-effect waves-light btn red lighten-2">Add</button>
    </div>
    </form>
</div>

<div id="update_transaction" class="modal modal-fixed-footer" >
    <div class="modal-header red lighten-2 white-text row">
        <div class="col s10">
            <h4>Edit Transaction</h4>
        </div>
        <div class="col s2">
            <a href="#" id="update_transaction_delete" class="white-text">
                <i class="fa fa-trash right-align center fa-3x"></i>
            </a>
        </div>
    </div>
    <div class="modal-content">
        <div class="row">
            <form class="col s12" onsubmit="return false">
                <input id="update_transaction_id" type="hidden">
                <div class="input-field col s12" onclick="$('#category').modal('open');">
                    <i class="prefix" id="update_transaction_category_icon"><img class="circle responsive-img" src="img/icon_not_selected.png"></i>
                    <input id="update_transaction_category" type="text" placeholder="Category" required>
                    <input id="update_transaction_category_id" type="hidden">
                </div>
                <div class="input-field col s12">
                    <i class="fa fa-dollar prefix"></i>
                    <input id="update_transaction_amount" type="number" placeholder="How much?" required>
                </div>
                <div class="input-field col s12">
                    <i class="fa fa-pencil prefix"></i>
                    <input id="update_transaction_note" type="text" placeholder="Note" required>
                </div>
                <div class="input-field col s12">
                    <i class="fa fa-calendar prefix"></i>
                    <input id="update_transaction_date" type="date" placeholder="Date" class="datepicker" required>
                </div>
                <div class="input-field col s12" onclick="$('#wallet').modal('open');">
                    <i class="prefix" id="category_icon"><img class="circle responsive-img" src="img/wallet.png"></i>
                    <input id="update_transaction_wallet" type="text" placeholder="Wallet">
                    <input id="update_transaction_wallet_id" type="hidden">
                </div>
        </div>

    </div>

    <div class="modal-footer">
        <button id="update_transaction_button" class="modal-action waves-effect waves-light btn red lighten-2">Update</button>
    </div>
    </form>
</div>
<div id="add_wallet" class="modal modal-fixed-footer">
    <div class="modal-header red lighten-2 white-text">
        <h4>Add wallet</h4>
    </div>
    <div class="modal-content">
		 <div class="row">
		<form class="col s12" onsubmit="return false">
		<div class="input-field col s12">
          <i class="fa fa-money prefix"></i>
          <input id="add_wallet_name" type="text" placeholder="Your wallet name?" required>
        </div>
		<div class="input-field col s12" onclick="$('#currency').modal('open');">
          <i class="fa fa-dollar prefix" id="currency_icon"></i>
          <input id="add_wallet_currency" type="text" placeholder="Currency" required>
          <input id="add_wallet_currency_id" type="hidden">
        </div>
		<div class="input-field col s12">
          <i class="fa fa-money prefix"></i>
          <input id="add_wallet_startAmount" type="number" placeholder="Start amount" required>
        </div>

	  </div>
    </div>

    <div class="modal-footer">
        <button id="add_wallet_button" class="modal-action waves-effect waves-light btn red lighten-2">Add</button>
    </div>
    </form>
</div>