
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,"><!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Đăng nhập | Hệ thống quản lý tài chính cá nhân</title>

    <!-- CORE CSS-->


    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/materialize.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/materialize.min.js'))
        ->prependFile($this->basePath('js/login.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ?>
</head>

<body>
<!-- Mixins-->
<div class="pen-title">
    <h1>Hệ thống quản lý tài chính cá nhân</h1><span>Code <i class='fa fa-code'></i> by <a rel="nofollow" rel="noreferrer"href='http://facebook.com/draku2'>Draku</a></span>
</div>
<div class="container">
    <div class="card"></div>
    <div class="card">
        <h1 class="title">Đăng nhập</h1>
        <form id="login"  onsubmit="return false">
            <div class="input-container">
                <input type="email" id="login_email" required="required"/>
                <label for="login_email">Email</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" id="login_password" required="required"/>
                <label for="login_password">Mật khẩu</label>
                <div class="bar"></div>
            </div>
            <div class="button-container">
                <button><span>Go</span></button>
            </div>
            <!--<div class="footer"><a rel="nofollow" rel="noreferrer"href="#">Forgot your password?</a></div>-->
        </form>
    </div>
    <div class="card alt">
        <div class="toggle"></div>
        <h1 class="title">Đăng ký
            <div class="close"></div>
        </h1>
        <form id="register"  onsubmit="return false">
            <div class="input-container">
                <input type="email" id="register_email" required="required"/>
                <label for="register_email">Email</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="text" id="register_name" required="required"/>
                <label for="register_name">Tên của bạn</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" id="register_password" required="required"/>
                <label for="register_password">Mật khẩu</label>
                <div class="bar"></div>
            </div>
            <div class="input-container">
                <input type="password" id="register_password_retype" required="required"/>
                <label for="register_password_retype">Nhập lại Mật khẩu</label>
                <div class="bar"></div>
            </div>
            <div class="button-container">
                <button><span>Gửi đi</span></button>
            </div>
        </form>
    </div>
</div>

</body>

</html>